### ISSUE TITLE
Deploy latest version to PyPI

### ISSUE THREAD

**Issue by varunagrawal** [jonsafari/nvidia-ml-py#1]
It seems the latest version of this code isn't available on PyPI since the package version fails on line 1831 due to missing parentheses, but this has already been fixed here.

It would be great if you could push the latest version to the PyPI index.

**Comment by mholt** [comment]
+:100: from me and a bunch of other people using this in `glances`.

**Comment by jonsafari** [comment]
Unfortunately I don't have time now to maintain this code, so please fork it and implement these suggestions.

**Comment by varunagrawal** [comment]
In that case, can you please transfer ownership of the PyPI package to me? It would be nice to maintain continuity.

I am `varunagrawal` on PyPI

**Comment by varunagrawal** [comment]
@jonsafari can you also please add me as an owner on PyPI? I can then update the current package rather than create a new one.

**Comment by jonsafari** [comment]
Nvidia is the owner on PyPI:  https://pypi.python.org/pypi/nvidia-ml-py/7.352.0

**Comment by varunagrawal** [comment]
Would it be possible to connect me with whoever maintains this at Nvidia?

**Comment by jonsafari** [comment]
I don't know who exactly at Nvidia maintains this.  The installation code lists nvml-bindings@nvidia.com , so try that address.

**Comment by varunagrawal** [comment]
Great! Thank you Jon.

**Comment by jonsafari** [comment]
Good luck!
